### ISSUE TITLE
Mojo Marketplace plugin interfering with "Featured", "Popular", and "Reccomended" section of the Add New Plugin page

### ISSUE THREAD

**Issue by miles-cm** [mojoness/mojo-marketplace-wp-plugin#10]
When activated, "Featured", "Popular", and "Reccomended" section of the Add New Plugin page do not load completely, almost as though the connection between the site and wordpress.org is being interrupted somehow. This appears to be a bug. 

The symptoms include, 
- On the **Plugins** > **Add New** page of /wp-admin/, Featured plugins do not show up. Instead a message which reads "An unknown error occurred". [Screenshot](https://i.imgur.com/ejG6coG.png) 
- Periodically a message which reads "The plugin `mojo-marketplace-wp-plugin/mojo-marketplace.php` has been deactivated due to an error: Plugin file does not exist." appears on the **Plugins** page of /wp-admin/. [Screenshot](https://i.imgur.com/DdBE9qu.png) 

Searching for plugins and themes works without issue, installing plugins works without issue, but the  "Featured", "Popular", and "Reccomended" section of the Add New Plugin page do not work, whenever this plugin is active.

Same results using php version 5.6.17, 5.4.43, 5.2.17.

I created a test WordPress site, with no plugins other than Mojo Marketplace installed, tried several default themes (twentyfourteen, twentyfifteen, twentysixteen) on the latest WP Version, same issue. https://miles.cm/mojo-test-site/

**Comment by MikeHansenMe** [comment]
Thanks for letting us know. I will look at this immediately.

**Comment by MikeHansenMe** [comment]
It appears to be in the updater.  Still working on it.

**Comment by MikeHansenMe** [comment]
Found the issue. Fixed in [https://github.com/mojoness/mojo-marketplace-wp-plugin/commit/a3d87370b4c3744e06d31daa57b9c04a2cb5ae45](url)

**Comment by MikeHansenMe** [comment]
Going to push an update to all the install channels and trigger updates via the updater.

Thank you @miles-cm for the detailed issue.
