### ISSUE TITLE
Error Message with User Accounts

### ISSUE THREAD

**Issue by livylynn** [mojoness/mojo-marketplace-wp-plugin#23]
Hello, I've created User Accounts for Contributors to my blog, but when I log into their accounts to test and see if they're working, this error message is posted: 

**Warning: array_search() expects parameter 2 to be array, null given in /home5/theblvc3/public_html/hollywoodlassie/wp-content/plugins/mojo-marketplace-wp-plugin/inc/menu.php on line 42

Warning: Cannot modify header information - headers already sent by (output started at /home5/theblvc3/public_html/hollywoodlassie/wp-content/plugins/mojo-marketplace-wp-plugin/inc/menu.php:42) in /home5/theblvc3/public_html/hollywoodlassie/wp-admin/includes/misc.php on line 1116

Warning: Cannot modify header information - headers already sent by (output started at /home5/theblvc3/public_html/hollywoodlassie/wp-content/plugins/mojo-marketplace-wp-plugin/inc/menu.php:42) in /home5/theblvc3/public_html/hollywoodlassie/wp-includes/option.php on line 919

Warning: Cannot modify header information - headers already sent by (output started at /home5/theblvc3/public_html/hollywoodlassie/wp-content/plugins/mojo-marketplace-wp-plugin/inc/menu.php:42) in /home5/theblvc3/public_html/hollywoodlassie/wp-includes/option.php on line 920** 

When I click on 'Create New Post' then 'Submit Post' this same message comes up, and users are not able to submit posts. Help?

**Comment by MikeHansenMe** [comment]
Ill take a look at this now. Thanks for letting us know.

**Comment by MikeHansenMe** [comment]
Just pushed an update( https://github.com/mojoness/mojo-marketplace-wp-plugin/commit/c804dd047c821f9b6c9189b33ee3d52931f10cdf ). We will get this rolled out with the next update. Thanks again!
