### ISSUE TITLE
Error when viewing plugins page

### ISSUE THREAD

**Issue by The-Fireplace** [mojoness/mojo-marketplace-wp-plugin#25]
When I visit the plugins in wp-admin, I see the following error (I have enabled WP_DEBUG and WP_DEBUG_DISPLAY):
PHP Notice:  Undefined variable: branded_plugin_details in [path shortened]/wp-content/plugins/mojo-marketplace-wp-plugin/inc/branding.php on line 39

WordPress 4.9.6
MOJO Marketplace 1.3.4

**Comment by MikeHansenMe** [comment]
thanks for reporting this issue. I will look into it.

**Comment by MikeHansenMe** [comment]
This should be resolved by https://github.com/mojoness/mojo-marketplace-wp-plugin/commit/8d274f0a427999bf64689f0ffa5e9b01ce2aae30. That will go out with the next release of the plugin.
