### ISSUE TITLE
Plugin name and description changes after activation/deactivation

### ISSUE THREAD

**Issue by ianbelanger79** [mojoness/mojo-marketplace-wp-plugin#34]
When the plugin is active on a Bluehost box, the plugin name is listed as Bluehost. After deactivating the plugin, the name changes to MOJO Marketplace. The description is also different after deactivating. This could really cause confusion for the average user.

For instance, let's say that they have an issue with WP and are told to deactivate all plugins. They probably won't reactivate a plugin named MOJO Marketplace, because they probably have no idea that it is in fact, the Bluehost plugin.

**Comment by earnjam** [comment]
This is because the plugin is used in multiple brands and not something we can really fix since you can't change what is displayed when the plugin is not active. It will also be resolved once we release the separate Bluehost specific version.
