### ISSUE TITLE
Error on WordPress Updates page

### ISSUE THREAD

**Issue by The-Fireplace** [mojoness/mojo-marketplace-wp-plugin#36]
When I visit the WordPress Updates page in wp-admin, I see the following error (I have enabled WP_DEBUG and WP_DEBUG_DISPLAY):
Notice: Undefined index: mojo-marketplace-wp-plugin/mojo-marketplace.php in [path shortened]/wp-content/plugins/mojo-marketplace-wp-plugin/updater.php on line 14

WordPress 4.9.8
MOJO Marketplace 1.3.4

**Comment by MikeHansenMe** [comment]
@The-Fireplace thanks for the report. We will get this looked into right away.

**Comment by ianbelanger79** [comment]
Hi @The-Fireplace,

I have been working to try and recreate the error, without much luck. Could you please share with me some more details about the site you are seeing the error on?

- Active plugins
- Active theme
- Hosting provider

Thank you

**Comment by ianbelanger79** [comment]
This issue has been fixed with an update to the updater array which changed the value of the current version of the plugin. I am closing this issue due to the issue being fixed.
