### ISSUE TITLE
Bluehost homepage layout "breaks" at some viewport widths

### ISSUE THREAD

**Issue by ianbelanger79** [mojoness/mojo-marketplace-wp-plugin#49]
The responsiveness of the Bluehost/MOJO homepage needs to be adjusted to work better on all screen widths
![bh-plugin-breaks-layout](https://user-images.githubusercontent.com/34601694/47302803-677e5500-d5f0-11e8-8397-759287dda478.PNG)
![bh-plugin-breaks-layout2](https://user-images.githubusercontent.com/34601694/47302805-677e5500-d5f0-11e8-97da-025d8302041a.PNG)

**Comment by wpscholar** [comment]
Brain dump: This is probably due to a discrepancy between the grid system assuming it is using the entire viewport and it actually getting only a portion of the viewport. Not sure what grid system is in use, but maybe a more fluid layout where rows are defined would be better?

**Comment by earnjam** [comment]
It's Bootstrap v3

https://github.com/mojoness/mojo-marketplace-wp-plugin/blob/bf799b5b982a6db68d701ea802654246ee46693c/inc/styles.php#L6

**Comment by earnjam** [comment]
I think there are a few issues at play. 
1) The headers are not inside containers with the grid system classes. So they don't stay on their own lines properly. 
2) The blog post panel has an extra link, making it longer than pages panel before they break to a single column
3) The WooCommerce logo and long button label wreck that panel. 

I think if we just clean up the markup a bit, it should all work fine.

**Comment by ianbelanger79** [comment]
Closed via #50
