### ISSUE TITLE
Distributed files to customers should not have the .git files included

### ISSUE THREAD

**Issue by carl-alberto** [mojoness/mojo-marketplace-wp-plugin#79]
Hopefully the releases https://github.com/mojoness/mojo-marketplace-wp-plugin/releases
given to customers would include the vendor files and the git files are not included so it won't mess up with hosting with internal git.

Thanks!

**Comment by earnjam** [comment]
The package that is installed on the hosting environments is not delivered from the GitHub releases page. We tag releases here to signify a new version, but it goes through a build process and then is delivered to the hosting accounts from another location. 

Have you seen an instance where a site has gotten an unbuilt version of the plugin (i.e. missing vendor folder, or including dev only files such as `.git`)?

**Comment by earnjam** [comment]
Since #78 we also attach a zipped, built version of the plugin to the releases page with each tagged release. So anyone installing this manually can use that zip and not have to do a build, remove the `.git` directory, etc.

**Comment by carl-alberto** [comment]
Sorry for the lack of response, we just saw it from a customer having issues and we advised to manually remove the gitignore file. Glad to hear that the release did not have the .git files and we will just refer the customers in that release package. Thanks @earnjam !

**Comment by earnjam** [comment]
@carl-alberto No worries! If you encounter an instance of extraneous files being installed again, feel free to update here and we can investigate further.
